version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres-lowschool
    restart: unless-stopped
    environment:
      POSTGRES_USER: lowschool
      POSTGRES_PASSWORD: lowschool123
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - "./lowschool:/var/lib/postgresql/data"
      
# postgresql://admin:password123@localhost:5432/mi_base_datos
# postgresql://lowschool:lowschool123@localhost:5432/school_db